### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by ianacaburian** [ianacaburian/ssm-project-template#1]
## Tasks
- [x] Set up repo CMake infrastructure.
- [x] Set up tests for HelloWorld app.
- [x] Fix all build warnings/errors.
- [x] Set up Actions and pass all status checks.
