### ISSUE TITLE
Add plugin val to CI

### ISSUE THREAD

**Issue by ianacaburian** [ianacaburian/ssm-project-template#3]
### Tasks
- [x] Set plugin val to CI
- [x] Lock SSM::Core to version 0.0.3
- [x] Fix: pluginval failing on release build
